export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_TOPSALES_REQUEST = 'FETCH_TOPSALES_REQUEST';
export const FETCH_TOPSALES_SUCCESS = 'FETCH_TOPSALES_SUCCESS';
export const FETCH_TOPSALES_FAILURE = 'FETCH_TOPSALES_FAILURE';
